### ISSUE TITLE
Problems with height of the iframe: only displays top part

### ISSUE THREAD

**Issue by numeroteca** [INN/pym-shortcode#14]
I am testing the plugin. Everything works fine except the height of the iframe, it only shows half of the top part of the iframe:
http://bilbaodatalab.wikitoki.org/2017/01/10/workflow-de-un-proyecto-de-datos/#datavis

I am trying to embed this [responsive scatter plot](http://wikitoki.org/bilbaodatalab/lab/diagrama-dispersion/) in a post and this is how it looks:
![page-shot-2017-2-2 workflow de un proyecto de datos](https://cloud.githubusercontent.com/assets/1223722/22554288/dc3e2804-e95f-11e6-9ae7-42f5ec2719c3.png)

**Comment by numeroteca** [comment]
This is the code I've added this to my child page:
```
<script src="http://bilbaodatalab.wikitoki.org/wp-content/plugins/pym-shortcode/js/pym.js"></script>
<script>
var pymChild = new pym.Child({ renderCallback: resize });
</script>
```

**Comment by benlk** [comment]
This looks like a problem with the render callback in the child page; it looks like it's not defined.

Using Chrome's [DevTools console](https://developers.google.com/web/tools/chrome-devtools/console/), I see the following error message:

> index.html?initialWidth=535&childId=pym_0&parentUrl=http%3A%2F%2Fbilbaodatalab.wikitoki.org%2F2017%…:213 Uncaught ReferenceError: **resize is not defined**
    at index.html?initialWidth=535&childId=pym_0&parentUrl=http%3A%2F%2Fbilbaodatalab.wikitoki.org%2F2017%…:213
(anonymous) @ index.html?initialWidth=535&childId=pym_0&parentUrl=http%3A%2F%2Fbilbaodatalab.wikitoki.org%2F2017%…:213

That's this line in http://wikitoki.org/bilbaodatalab/lab/diagrama-dispersion/index.html:
```
var pymChild = new pym.Child({ renderCallback: resize });
```

You might start there, since you've obviously defined a function resize here:
```  
  // Assign a listener to the resize event
  window.onresize = resize;
  
  function resize() {
```

This doesn't look like an issue with the Pym Shortcode, though, so I'm going to close this issue.
