### ISSUE TITLE
React is dropping className for class

### ISSUE THREAD

**Issue by benlk** [INN/pym-shortcode#47]
Keep an eye on https://github.com/facebook/react/issues/13525 and update this plugin when Gutenberg switches from `className` to `class`. 

- [ ] add a deprecated block method to support upgrading from `className` to `class`
- [ ] are changes in the shortcode necessary? Do those too.
- [ ] changelog docs

**Comment by dkoo** [comment]
There was a [more recent update](https://github.com/facebook/react/issues/13525#issuecomment-499196939) which suggests that work on this has paused for the foreseeable future, and [another more recent update](https://github.com/facebook/react/issues/13525#issuecomment-671892643) which suggests that dropping `className` for `class` might not be happening at all:

> I think it's plausible we'll revisit this in the future, or at least make class not warn and let people do what they want. But for now, we'll shelving this idea.

Based on this, I think we should close this issue since it's not a planned change at this time.
