### ISSUE TITLE
Make pym path configurable

### ISSUE THREAD

**Issue by coreyhaines** [INN/pym-shortcode#6]
Unfortunately, the version of pym that is bundled here is buggy in certain cases. Also, as changes get made, this means we would have to update this repository and update the wordpress site.
Making the pym path configurable would make it easier to keep up with changes without having to redeploy this plugin.

**Comment by benlk** [comment]
The optional `pymsrc` attribute in the shortcode allows you to load a specified version of Pym instead of the default version.

```
[pym src="child.html" pymsrc="https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.5/pym.min.js"]
```

In this example, the version of Pym loaded on the parent page would be https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.5/pym.min.js instead of the version used by this plugin.

**Comment by coreyhaines** [comment]
WOOHOO! Thanks! Guess I should have read the full manual.

Is this becoming default for Largo sites? We have a few customers that are largo-based and hopefully many many more. We use our custom pym, and hoping we won't run into issues. We are definitely NOT compatible with the NPRApps version of pym these days.

**Comment by aschweigert** [comment]
@coreyhaines yep, this will become our standard approach. let me know if this causes any issues for you and we'll see what we can do to address them
